### ISSUE TITLE
Breaking oak hanging signs drops a rainbow hanging sign

### ISSUE THREAD

**Issue by Thepowerisreal** [Wolren/PrideLand#1]
Tested on the latest release, I have not attempted it on any other wood types.

**Comment by Wolren** [comment]
I reproduced the bug, it affects both normal and hanging oak signs. It was caused by inutile data generation lines as wall signs don't require adding loot table. It somehow caused generation to create files overriding default oak sign tables.
![image](https://github.com/Wolren/PrideLand/assets/86470291/f65bf388-62c6-4229-837d-88d03eed50f3)
I'll update all the files tomorrow with 1.0.2
